dist: xenial

language: go
go:
  - "1.12.x"

cache:
  directories:
    - $GOPATH/pkg/mod

go_import_path: github.com/coredns/coredns

git:
  depth: 1

branches:
  only:
  - master

env:
  - TEST_TYPE=coverage
  - TEST_TYPE=integration
  - TEST_TYPE=core
  - TEST_TYPE=plugin

# In the Travis VM-based build environment, IPv6 networking is not
# enabled by default. The sysctl operations below enable IPv6.
# IPv6 is needed by some of the CoreDNS test cases.

deploy:
  provider: script
  script: bash bin/docker_build
  on:
    branch: twentyfourbytes

script:
  - make TEST_TYPE=$TEST_TYPE travis

